Using vfs hook for penrose.

diff --git a/.github/workflows/build_kernel_blackshark4_miui_a11.yml b/.github/workflows/build_kernel_blackshark4_miui_a11.yml
--- a/.github/workflows/build_kernel_blackshark4_miui_a11.yml
+++ b/.github/workflows/build_kernel_blackshark4_miui_a11.yml
@@ -243,13 +243,17 @@ jobs:
       - name: Patch Kernel for no-kprobe
         run: |
           cd $GITHUB_WORKSPACE
-          if [[ -f "/tmp/Patches/patches.sh" ]]; then
-            cp /tmp/Patches/patches.sh device_kernel/
-            cd device_kernel
-            bash patches.sh
-          else
-            echo "Cannot found patches.sh in build project , please check u file existed in build project !"
-          fi
+          # if [[ -f "/tmp/Patches/patches.sh" ]]; then
+            # cp /tmp/Patches/patches.sh device_kernel/
+            # cd device_kernel
+            # bash patches.sh
+          # else
+            # echo "Cannot found patches.sh in build project , please check u file existed in build project !"
+          # fi
+          cd $GITHUB_WORKSPACE/device_kernel
+          git clone https://github.com/JackA1ltman/NonGKI_Kernel_Patches.git -b mi_kernel
+          cp NonGKI_Kernel_Patches/testing_vfs_hook.patch ./
+          patch -p1 < testing_vfs_hook.patch || true
 
       - name: Extra Kernel Options
         run: |
